name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node
        uses: volta-cli/action@v1

      - name: init
        run: npm ci

      - name: inspect
        run: npm run inspect

      - name: test
        run: npm run test:report

      - name: build
        run : npm run build
